### ISSUE TITLE
Improve the  Readme.md and data.md.

### ISSUE THREAD

**Issue by I-am-sayantan** [I-am-sayantan/public-sentiment-analysis-based-on-twitter-hashtags#2]
# :bookmark_tabs: Documentation

**If you are able to understand the tasks of the project, then you add some more parts in the [Readme.md](https://github.com/I-am-sayantan/public-sentiment-analysis-based-on-twitter-hashtags/blob/main/README.md) and in  [data.md](https://github.com/I-am-sayantan/public-sentiment-analysis-based-on-twitter-hashtags/blob/main/datasets/data.md)**

_1.  as you can add new parts in the readme, like research papers in this domain, kaggle solutions and Github links, and put the name as **supporting material** 
2.  You can make the abstract better.
3.  Add more points to the data.md and describe more about the columns, as well more observational points._

**Comment by aditimaurya** [comment]
I'd like to work on this.

**Comment by I-am-sayantan** [comment]
> I'd like to work on this.

Defenitely

**Comment by I-am-sayantan** [comment]
This is issue is fixed

**Comment by I-am-sayantan** [comment]
This is an issue, fixed by @aditimaurya
