### ISSUE TITLE
Make sentiment scores from the tweets of the hashtags using dataset.csv

### ISSUE THREAD

**Issue by I-am-sayantan** [I-am-sayantan/public-sentiment-analysis-based-on-twitter-hashtags#3]
### :pencil: TASK 1: 
Make a jupyter notebook, in which you can write the codes to find the sentiment scores of the tweets from the dataset.csv.

-  **About the task** : _For better understanding, please have a look here: [TASK 1](https://github.com/I-am-sayantan/public-sentiment-analysis-based-on-twitter-hashtags#tasks-pencil2-)_
-  **contribution** : _For making a contribution please have look here: [Contribute](https://github.com/I-am-sayantan/public-sentiment-analysis-based-on-twitter-hashtags#how-to-contribute-smiley-)_
-  **Format** : _Format of the jupyter notebook should be [this ](https://github.com/I-am-sayantan/public-sentiment-analysis-based-on-twitter-hashtags/blob/main/CONTRIBUTION/Jupyter%20notebooks/Sayantan_kirtaniya.ipynb): **only till part 1**, and name should be Name_of_contributer.ipynb_ 
- **Output** : Here is a sample snippet of the output after adding the scores

<p align="center">
  <kbd>
  <img width="500" height="100" src="https://user-images.githubusercontent.com/50532530/144595141-810f844f-459a-4662-9ec1-9eea86fc44eb.png">
   </kbd> 
</p>

Since there are multiple algorithms for making the scores, multiple contributors can participate in it and make their own notebook as a contribution.

**Comment by preyam2002** [comment]
> Can I start working on it?

**Comment by I-am-sayantan** [comment]
@preyam2002 go ahead please , I am giving you the role in the discord server

**Comment by I-am-sayantan** [comment]
> I would like to work in this task.

Definitely go ahead, we will welcome your PR

**Comment by aaryan20** [comment]
Hello, I'd like to work on this task

**Comment by I-am-sayantan** [comment]
> Hello, I'd like to work on this task

Sure go ahead, join the discord server for the doubts clarifications.

**Comment by beerukuri** [comment]
I like to work on this task

**Comment by I-am-sayantan** [comment]
> I like to work on this task

Sure go ahead, use the discord server for the doubts clarifications.

**Comment by Rudransh1084** [comment]
I would like to work on this

**Comment by rahulgupta9202** [comment]
I want to work on this.

**Comment by I-am-sayantan** [comment]
> I would like to work on this

sure I am assigning

**Comment by I-am-sayantan** [comment]
> I want to work on this.

sure I am assigning

**Comment by Peaceful-555** [comment]
I would like to work on this.

**Comment by I-am-sayantan** [comment]
> I would like to work on this.

Sure I am assigning

**Comment by asaraf7** [comment]
I've would like to work on this.

**Comment by sm745052** [comment]
heyy.. I want to work on this

**Comment by Jeevesh28** [comment]
I would like to work on this

**Comment by I-am-sayantan** [comment]
> I'd like to work on this. But I don't use a Jupyter notebook. Is it okay if I give a .py file?

yes, I assigned it, please make a jupyter notebook, you can use google colab, the problem will come in the plotting task for that It has to be in the jupyter, as well as in notebooks its easy to visualize the data.

**Comment by Smruti2002** [comment]
I would also like to work on it

**Comment by I-am-sayantan** [comment]
> I would also like to work on it

Definitely start working.

**Comment by kirtii7** [comment]
I would like to work on it too!

**Comment by I-am-sayantan** [comment]
> I would like to work on it too!

Please go ahead, join the server for doubts clarifications

**Comment by asaraf7** [comment]
> > I'd like to work on this. But I don't use a Jupyter notebook. Is it okay if I give a .py file?
> 
> yes, I assigned it, please make a jupyter notebook, you can use google colab, the problem will come in the plotting task for that It has to be in the jupyter, as well as in notebooks its easy to visualize the data.

Could you please help me with google colab :) 
How to use the dataset and other files and how to download required libraries..

**Comment by I-am-sayantan** [comment]
> > > I'd like to work on this. But I don't use a Jupyter notebook. Is it okay if I give a .py file?
> 
> > 
> 
> > yes, I assigned it, please make a jupyter notebook, you can use google colab, the problem will come in the plotting task for that It has to be in the jupyter, as well as in notebooks its easy to visualize the data.
> 
> 
> 
> Could you please help me with google colab :) 
> 
> How to use the dataset and other files and how to download required libraries..

Just use internet, it's really easy or watch a video, it's really easy.

**Comment by I-am-sayantan** [comment]
Closing this issue , thanks for the contributions
