### ISSUE TITLE
Make plots from the scores created from TASK 1 

### ISSUE THREAD

**Issue by I-am-sayantan** [I-am-sayantan/public-sentiment-analysis-based-on-twitter-hashtags#4]
### :pencil: TASK 2: 
After completing #3  you can make the plots from the scores and complete task 2 of this project. This task should be done in the same notebook in which you had done task 1.

-  **About the task** : _For better understanding, please have a look here: [TASK 2](https://github.com/I-am-sayantan/public-sentiment-analysis-based-on-twitter-hashtags#tasks-pencil2-)_
-  **contribution** : _For making a contribution please have look here: [Contribute](https://github.com/I-am-sayantan/public-sentiment-analysis-based-on-twitter-hashtags#how-to-contribute-smiley-)_
-  **Format** : _Format of the jupyter notebook should be [this ](https://github.com/I-am-sayantan/public-sentiment-analysis-based-on-twitter-hashtags/blob/main/CONTRIBUTION/Jupyter%20notebooks/Sayantan_kirtaniya.ipynb): **part1 + part 2**, and name should be Name_of_contributer.ipynb_ 
- **Output**: You can make line plots, bar plots, pie charts etc from the dataset.

<p align="center">
  <kbd>
  <img width="300" height="200" src="https://user-images.githubusercontent.com/50532530/144600542-5783994b-6fa3-473c-bed3-40cf50484642.gif">
   </kbd> 
</p>

Since a person can make multiple plots and make different observations from them, multiple contributors can participate in it and make their own notebook as a contribution.

**Comment by Rudransh1084** [comment]
I want to like to work on this

**Comment by rahulgupta9202** [comment]
I want to work on this

**Comment by I-am-sayantan** [comment]
> I would like to work on this

Yes start working

**Comment by I-am-sayantan** [comment]
> I want to work on this
> 
> 
> 
> 

Definitely

**Comment by prrtk** [comment]
I would like to work on this.

**Comment by I-am-sayantan** [comment]
> I would like to work on this. 

Please start working

**Comment by prrtk** [comment]
Thank you

**Comment by Smruti2002** [comment]
I would like to work on this

**Comment by I-am-sayantan** [comment]
> I would like to work on this
> 
> 

Please go ahead, I'll assign

**Comment by Jeevesh28** [comment]
I would like to work on this

**Comment by rohitpadage** [comment]
i would like to work on this issue...

**Comment by I-am-sayantan** [comment]
> i would like to work on this issue...

please go ahead

**Comment by beerukuri** [comment]
I would like to work on this

**Comment by I-am-sayantan** [comment]
> I would like to work on this

Please go ahead

**Comment by Peaceful-555** [comment]
I would like to work on this.

**Comment by I-am-sayantan** [comment]
> I would like to work on this.

Sure I'll assign.

**Comment by I-am-sayantan** [comment]
**_GOOD WORK EVERYONE CLOSING THE ISSUE NOW_**
